server:
  port: 0

spring:
  application:
    name: transaction-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.99.141:3306/transaction?useSSL=false
    username: root
    password: root

api:
  default: https://api.bithumb.com

management:
  endpoints:
    web:
      exposure:
        include: health