spring:
  datasource:
    url: jdbc:mysql://3.37.127.25:3306/transaction?useSSL=false
    username: transactionuser
    password: user1234
  kafka:
    bootstrap-servers: 3.37.127.25:9092

api:
  default: https://api.bithumb.com
logging:
  file:
    name: "/log/transaction-manager.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB
  pattern:
    console:

management:
  endpoints:
    web:
      exposure:
        include: health