server:
  port: 8080

spring:
  application:
    name: transaction-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.209.68.198:3306/transaction?useSSL=false
    username: transactionuser
    password: user1234

  kafka:
    bootstrap-servers: 13.209.68.198:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer



api:
  default: https://api.bithumb.com

management:
  endpoints:
    web:
      exposure:
        include: health