server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/test?useSSL=false
  #    username: root
  #    password: ms159753
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

logging:
  level:
    com.verifymycoin.TransactionManager: DEBUG
    org.hibernate: info

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,info
