server:
  port: 0

spring:
  application:
    name: transaction-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  jpa:
    database: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

api:
  default: https://api.bithumb.com
